[package]
name = "simd-json"
version = "0.3.8"
authors = ["Heinz N. Gies <heinz@licenser.net>", "Sunny Gleason"]
edition = "2018"
exclude = [ "data/*", "fuzz/*"]
license = "Apache-2.0/MIT"
description = "High performance JSON parser based on a port of simdjson"
repository = "https://github.com/simd-lite/simd-json"
readme = "./README.md"
documentation = "https://docs.rs/simd-json"

[workspace]


[dependencies]
halfbrown = "0.1"

value-trait = "0.1.7"

# serde compatibilty
serde = { version = "1", features = ["derive"], optional = true}
serde_json = { version = "1", optional = true}

jemallocator = { version = "0.3", optional = true }
perfcnt = { version = "0.5", optional = true }
getopts = { version = "0.2", optional = true }
colored = { version = "1.9", optional = true }
simd-lite = { version = "0.1.0", optional = true }
beef = { version = "0.4.1", optional = true }

# for float comparison
float-cmp = "0.6"

# because dev dependenceis can't be optional ...
alloc_counter = {version = "0.0.4", optional = true}

[dev-dependencies]
getopts = "0.2"
proptest = "0.9"
serde_derive = "1"
serde_bytes = "0.11"
criterion = "0.3"
#criterion = { path = "../criterion.rs" }
core_affinity = "0.5"


[[bench]]
name = "parse"
harness = false


[features]
default = ["swar-number-parsing", "serde_impl"]
# Support for 128 bit integers
128bit = ["value-trait/128bit"]
# used for enabeling known keys in favour of a slower
# hasher that is not protected against hash collision
# attacks
known-key = [ "halfbrown/fxhash" ]
# use 8 number at once parsing strategy
swar-number-parsing = []
# serde compatibility
serde_impl = [ "serde", "serde_json", "halfbrown/serde" ]
# Support for ARM NEON SIMD
neon = ["simd-lite", "value-trait/neon"]
# Allow fallback to non simd CPUs
allow-non-simd = []
# for testing allocations
alloc = ["alloc_counter"]
# don't inline code - used for debugging
no-inline = []
# uses safe slice access ([]) instead of get_unsafe
# **for debugging**
safe = []
# also bench serde in the benchmarks
bench-serde = []
# use branch hints - requires nightly :(
hints = [] # requires nightly
# for perf testing, used by the example
perf = ["perfcnt", "getopts", "colored"]

[[example]]
name = "perf"

# [patch.crates-io]
# value-trait = { path = '../value-trait' }
